"""
Ch. 9 — Capstone: Word Frequency Analyzer

Reads a text file, counts word frequencies, saves results using both
pprint.pformat() (human-readable) and shelve (persistent storage),
then reloads from the shelf to display the top results.

Concepts used:
  - pathlib Path objects and path joining (concept 1)
  - Reading files with open() (concept 2)
  - Writing files with open() (concept 3)
  - Saving variables with shelve (concept 4)
  - Saving variables with pprint.pformat() (concept 5)
"""

import shelve
import pprint
from pathlib import Path

output_dir = Path(__file__).parent
input_file = output_dir / 'sample_text.txt'

# ------------------------------------------------------------------
# STEP 1: Read the text file
# ------------------------------------------------------------------

print("Reading:", input_file.name)

with open(input_file) as f:
    raw_text = f.read()

print(f"  {len(raw_text)} characters loaded.\n")

# ------------------------------------------------------------------
# STEP 2: Count word frequencies
# ------------------------------------------------------------------

# Normalize: lowercase everything so 'Python' and 'python' count as one word.
# Split on whitespace to get individual words.
# Strip punctuation from each word's edges so 'language.' == 'language'.
words = raw_text.lower().split()
cleaned_words = [word.strip('.,!?;:\'"()[]') for word in words]

# Build the frequency dict using the setdefault pattern from Ch. 5.
frequency = {}
for word in cleaned_words:
    if word:  # skip empty strings that may result from stripping
        frequency[word] = frequency.get(word, 0) + 1

print(f"Unique words found: {len(frequency)}")

# Sort by frequency descending so the most common words come first.
# sorted() with key= is the Pythonic way to sort a dict by value.
sorted_words = sorted(frequency.items(), key=lambda item: item[1], reverse=True)

print("\nTop 10 most frequent words:")
for word, count in sorted_words[:10]:
    print(f"  {word:<15} {count}")

# ------------------------------------------------------------------
# STEP 3: Save results as a human-readable .py file with pformat()
# ------------------------------------------------------------------

report_path = output_dir / 'frequency_report.py'

with open(report_path, 'w') as f:
    f.write('# Word frequency report — generated by 07_capstone_word_frequency.py\n\n')
    f.write('frequency = ' + pprint.pformat(frequency) + '\n\n')
    f.write('top_10 = ' + pprint.pformat(sorted_words[:10]) + '\n')

print(f"\nHuman-readable report saved to: {report_path.name}")
print("Open it in your editor — it's valid Python and fully readable.\n")

# ------------------------------------------------------------------
# STEP 4: Save results to a shelf for persistent storage
# ------------------------------------------------------------------

shelf_path = str(output_dir / 'frequency_shelf')

with shelve.open(shelf_path) as shelf:
    shelf['frequency'] = frequency
    shelf['top_10'] = sorted_words[:10]
    shelf['source_file'] = input_file.name
    shelf['word_count'] = len(cleaned_words)
    shelf['unique_count'] = len(frequency)

print("Shelf saved.")

# ------------------------------------------------------------------
# STEP 5: Reload from the shelf and display a summary
# ------------------------------------------------------------------

# This simulates a second script (or second run) loading previously saved results.
print("\n--- Reloading from shelf ---\n")

with shelve.open(shelf_path) as shelf:
    source = shelf['source_file']
    total_words = shelf['word_count']
    unique = shelf['unique_count']
    top_5 = shelf['top_10'][:5]

print(f"Source file   : {source}")
print(f"Total words   : {total_words}")
print(f"Unique words  : {unique}")
print(f"\nTop 5 words loaded from shelf:")
for word, count in top_5:
    bar = '#' * count
    print(f"  {word:<15} {count:>3}  {bar}")
